spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=900000

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
app.refresh-token.expiration-ms=1296000000