package com.rtxnano.ecommerce.order.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.UnsupportedJwtException;
import io.jsonwebtoken.security.Keys;
import io.jsonwebtoken.security.SignatureException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

/**
 * ==============================================================================
 * SERVICE: JwtTokenProvider (Zero-DB Stateless SSO)
 * ==============================================================================
 * Validates cryptographically signed HMAC-SHA256 JWT tokens generated by User Service
 * and constructs Spring Security Authentication principals in memory without database queries.
 */
@Component
public class JwtTokenProvider {

    private static final Logger log = LoggerFactory.getLogger(JwtTokenProvider.class);

    private final SecretKey signingKey;

    public JwtTokenProvider(@Value("${app.jwt.secret}") String jwtSecret) {
        if (jwtSecret == null || jwtSecret.isBlank()) {
            throw new IllegalArgumentException("app.jwt.secret must not be null or empty");
        }
        this.signingKey = Keys.hmacShaKeyFor(jwtSecret.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Parses and verifies the cryptographic signature and expiration of the JWT.
     */
    public boolean validateToken(String token) {
        if (token == null || token.isBlank()) {
            return false;
        }
        try {
            Jwts.parser()
                    .verifyWith(signingKey)
                    .build()
                    .parseSignedClaims(token);
            return true;
        } catch (SignatureException e) {
            log.warn("Invalid JWT signature: {}", e.getMessage());
        } catch (MalformedJwtException e) {
            log.warn("Invalid JWT token format: {}", e.getMessage());
        } catch (ExpiredJwtException e) {
            log.warn("JWT token is expired: {}", e.getMessage());
        } catch (UnsupportedJwtException e) {
            log.warn("Unsupported JWT token: {}", e.getMessage());
        } catch (IllegalArgumentException e) {
            log.warn("JWT claims string is empty: {}", e.getMessage());
        } catch (JwtException e) {
            log.warn("JWT validation exception: {}", e.getMessage());
        }
        return false;
    }

    /**
     * Extracts all claims from a validated token.
     */
    public Claims getClaims(String token) {
        return Jwts.parser()
                .verifyWith(signingKey)
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    /**
     * Resolves the user's unique UUID identifier from token claims.
     */
    public UUID extractUserId(String token) {
        Claims claims = getClaims(token);
        return resolveUserIdFromClaims(claims);
    }

    /**
     * Resolves the user's email address from token claims.
     */
    public String extractEmail(String token) {
        Claims claims = getClaims(token);
        String email = claims.get("email", String.class);
        if (email == null || email.isBlank()) {
            email = claims.getSubject();
        }
        return email;
    }

    /**
     * Extracts and normalizes user roles into Spring Security GrantedAuthorities.
     */
    public Set<GrantedAuthority> extractAuthorities(String token) {
        Claims claims = getClaims(token);
        return extractAuthoritiesFromClaims(claims);
    }

    /**
     * Builds a Spring Security Authentication token from a validated JWT.
     */
    public Authentication getAuthentication(String token) {
        Claims claims = getClaims(token);
        UUID userId = resolveUserIdFromClaims(claims);
        String email = claims.get("email", String.class);
        if (email == null || email.isBlank()) {
            email = claims.getSubject();
        }
        Set<GrantedAuthority> authorities = extractAuthoritiesFromClaims(claims);

        UserPrincipal principal = new UserPrincipal(userId, email, authorities);
        return new UsernamePasswordAuthenticationToken(principal, token, authorities);
    }

    private UUID resolveUserIdFromClaims(Claims claims) {
        String userIdStr = claims.get("userId", String.class);
        if (userIdStr == null || userIdStr.isBlank()) {
            userIdStr = claims.getSubject();
        }
        if (userIdStr == null || userIdStr.isBlank()) {
            throw new IllegalArgumentException("JWT contains no valid subject or userId claim");
        }

        try {
            return UUID.fromString(userIdStr);
        } catch (IllegalArgumentException e) {
            // If the subject is an email rather than a UUID string, derive a deterministic UUID
            return UUID.nameUUIDFromBytes(("user:" + userIdStr.trim().toLowerCase()).getBytes(StandardCharsets.UTF_8));
        }
    }

    private Set<GrantedAuthority> extractAuthoritiesFromClaims(Claims claims) {
        Set<GrantedAuthority> authorities = new HashSet<>();
        Object rolesObj = claims.get("roles");

        if (rolesObj instanceof Collection<?> rolesList) {
            for (Object role : rolesList) {
                if (role != null) {
                    String roleName = role.toString().trim();
                    if (!roleName.startsWith("ROLE_")) {
                        roleName = "ROLE_" + roleName;
                    }
                    authorities.add(new SimpleGrantedAuthority(roleName));
                }
            }
        } else if (rolesObj instanceof String rolesStr && !rolesStr.isBlank()) {
            for (String r : rolesStr.split(",")) {
                String roleName = r.trim();
                if (!roleName.isEmpty()) {
                    if (!roleName.startsWith("ROLE_")) {
                        roleName = "ROLE_" + roleName;
                    }
                    authorities.add(new SimpleGrantedAuthority(roleName));
                }
            }
        }

        // Default authority if none specified
        if (authorities.isEmpty()) {
            authorities.add(new SimpleGrantedAuthority("ROLE_CUSTOMER"));
        }

        return Collections.unmodifiableSet(authorities);
    }
}
